/*This function generates a random integer value from 0 to 3 */
function getComputerChoice(){
    return Math.floor(Math.random()*3);
}

/*This function takes the random integer value generated by getComputerChoice
 and return a string corresponding to one of the game choices*/
function getFormattedComputerChoice(computerSelection){
    if (computerSelection === 0){
        return "Rock";
    }
    if(computerSelection === 1){
        return "Paper";
    }
    if(computerSelection ===2){
        return "Scissors";
    }
    console.error("Something went wrong")

}

/*Take the input choice from the player and format it*/
function getPlayerSelection(){
    playerSelection = prompt("Enter Your Choice:");
    if(playerSelection){
        payerSelectionFormatted = playerSelection[0].toUpperCase() + (playerSelection.substr(1)).toLowerCase();
        return payerSelectionFormatted;
    }
    else{
        console.error("Please Enter A Choice!")
    }
    
}

/*Test the validity of the string inputted by the player*/
function isPlayerChoiceValid(playerSelection){
    if(playerSelection === "Rock" || playerSelection === "Paper" || playerSelection === "Scissors"){
        return true;
    }
}

/*The game itself, compares player and computer selection, decides the outcome of the match.*/
function playRound(playerSelection,computerSelection){
    lose_announcement = `You lost!${computerSelection} beats ${playerSelection}.`
    win_announcement =  `Congratulations You won!${computerSelection} lost to ${playerSelection}.`

    if(isPlayerChoiceValid(playerSelection)){
        if(playerSelection === computerSelection){
            return `Wow both are ${computerSelection}.It's a tie.What about another round?`
        }

        
        if(playerSelection === 'Rock'){
            if(computerSelection === 'Paper'){
                return lose_announcement;
            }
            if(computerSelection === 'Scissors'){
                return win_announcement;
            }
        }

        if(playerSelection === 'Paper'){
            if(computerSelection === 'Scissors'){
                return lose_announcement;
            }
            if(computerSelection === 'Rock'){
                return win_announcement;
            }
        }

        if(playerSelection === 'Scissors'){
            if(computerSelection === 'Rock'){
                return lose_announcement;
            }
            if(computerSelection === 'Paper'){
                return win_announcement;
            }
        }
    }

    else{
        console.error("Please Enter A Valid Choice!");
    }

}


computerSelection = getComputerChoice();
computerFormattedSelection = getFormattedComputerChoice(computerSelection);

playerSelection = getPlayerSelection();

console.log(playRound(playerSelection,computerFormattedSelection));